docs(changeset): add zod contract package
igorkamyshev/farfetched pull request #129
Opened 2022-10-01 10:56 UTC by Drevoed

resolves #117

2022-10-01 14:41 UTC, igorkamyshev requested changes
Thanks a lot 💙

However, I think, we have to provide at least minimal documentation before release. Could you add it?

2022-10-01 14:41 UTC, igorkamyshev commented on package.json
> +    "tslib": "^2.3.0"
Why do we need `tslib` for this integration? 🤔

2022-10-01 14:41 UTC, igorkamyshev commented on .changeset/fresh-years-float.md
> +add zod contract package
```suggestion
Add a complementary package for `zod` contracts
```

2022-10-01 14:41 UTC, igorkamyshev commented on .changeset/fresh-years-float.md
> +'@farfetched/zod': patch
patch will make release version 0.0.2, I assume it's better to release it as 0.1.0

```suggestion
'@farfetched/zod': minor
```

2022-10-01 14:41 UTC, igorkamyshev commented on packages/zod/src/__tests__/contract.test.ts
> +describe('runtypes/runtypeContract short', () => {
Could you add some more tests:
- for `.isData` method, now only `.getErrorMessages` is covered
- for more complex cases, like arrays or records

2022-10-01 14:41 UTC, igorkamyshev commented on packages/zod/src/__tests__/contract.type_spec.ts
> +expectType<Contract<unknown, string>>(contract);
Same here, I would like to have tests for type inference in more complex cases like records, arrays, optional fields.

2022-10-07 08:10 UTC, igorkamyshev requested changes
Thanks for the tests 🥹

I'm sorry that during PR development there are plenty of changes in repo tooling, tsc was replaced by rollup and jest was replaced by vitest. We have to support this changes in this PR before merging.

2022-10-07 08:10 UTC, igorkamyshev commented on packages/zod/.babelrc
> +        "useBuiltIns": "usage"
In other packages, we use `false` in the same case. Shall we change it there?

2022-10-07 08:10 UTC, igorkamyshev commented on packages/zod/jest.config.ts
> +export default {
😢 sorry for that, during this PR development I have replaces jest by vitetest. Could you migrate your package as well?

2022-10-07 08:10 UTC, igorkamyshev commented on packages/zod/project.json
> +      "executor": "@nrwl/js:tsc",
Also, you have migrate all builds from tsc to rollup. Could we do the same for this package?

2022-10-07 08:10 UTC, igorkamyshev commented on packages/zod/project.json
> +        "tsConfig": "packages/zod/tsconfig.lib.json",
Due to removing jest and migrating to rollup, it became unnecessary to have two different tsconfig filed. We can merge it to single one.

2022-10-07 08:10 UTC, igorkamyshev commented on packages/zod/project.json
> +      "executor": "@nrwl/jest:jest",
Here we have to replace executor with vitest as well.

2022-10-10 20:07 UTC, Drevoed commented
Sure, will rebase, should not be too bad

2022-10-13 13:45 UTC, igorkamyshev reviewed
Great job 💙

I guess, we will be ready to release it after minimal documentation provision 🤗

2022-10-14 05:32 UTC, igorkamyshev approved these changes
I've added links for docs to the site. Let's release it!

2022-10-14 05:43 UTC, merged