Cache params ordering issue
igorkamyshev/farfetched pull request #193
Opened 2022-11-30 21:03 UTC by Minhir

In the first commit, I represented the current problem with cache. Now, query params `{a: 1, b: 2}` and `{b: 2, a: 1}` are resolved as different ones.

In the second commit, I solved the problem with [fast-json-stable-stringify](https://www.npmjs.com/package/fast-json-stable-stringify) library as an example. I'm opened to discussion: maybe we will find another solution or hardcode stable-json-hash inside core package.

2022-12-01 10:47 UTC, igorkamyshev requested changes
Great idea 💙

However, I want to keep the core package with only one dependency — effector. So, I guess we can reimplement `fast-json-stable-stringify` inside package.

fixes #156

2022-12-11 10:28 UTC, igorkamyshev commented on packages/core/src/cache/lib/stable_stringify.ts
> +export function stableStringify(data: unknown): string | void {
🤓 а чому void?

2022-12-11 10:28 UTC, igorkamyshev approved these changes

2022-12-11 10:47 UTC, Minhir commented on packages/core/src/cache/lib/stable_stringify.ts
> +export function stableStringify(data: unknown): string | void {
```javascript
JSON.stringify(undefined) // undefined
```
:man_shrugging: 

https://evanhahn.com/when-stringify-doesnt-return-a-string/

https://github.com/microsoft/TypeScript/issues/18879 -- even in TS it's an issue

2022-12-15 18:23 UTC, Minhir commented
Will close https://github.com/igorkamyshev/farfetched/issues/156

2022-12-16 06:36 UTC, igorkamyshev commented on .changeset/brown-colts-refuse.md
> +'@farfetched/core': minor
```suggestion
'@farfetched/core': patch
```

2022-12-16 06:37 UTC, igorkamyshev approved these changes
Let's add changeset about fixes bug with un-serializable params? After that, we can ,erge it.

2022-12-17 03:26 UTC, merged