docs(changeset): Update type of useQuery. Added initialData type
igorkamyshev/farfetched pull request #203
Opened 2022-12-03 17:13 UTC by Bricks666

2022-12-03 17:14 UTC, Bricks666 commented
Update package for correct using with @farfetched/core >=0.3.0

2022-12-04 19:34 UTC, Bricks666 commented
@igorkamyshev

2022-12-05 01:56 UTC, igorkamyshev requested changes
Hello! Thanks for the fix 🤗

Could you add type_spec file for your fix to guarantee that the problem was there, and it is fixed now? All Farfetched PRs have to be tested before merge — https://farfetched.pages.dev/statements/tests.html

2022-12-05 01:56 UTC, igorkamyshev commented on .changeset/brave-rats-fetch.md
> +'@farfetched/react': minor
It is not minor, it is a fix of a bug. So, it is patch 🤗

```suggestion
'@farfetched/react': patch
```

2022-12-05 01:56 UTC, igorkamyshev commented on packages/react/package.json
> +  "version": "0.3.0",
Repository generates versions automatically, check README.md for more detailed development flow description. So, please revert this change.

2022-12-05 01:56 UTC, igorkamyshev commented on packages/react/src/use_query.ts
> +function useQuery<Params, Data, Error, InitialData>(
I think, this is the case for type tests 🤗

2022-12-07 06:36 UTC, igorkamyshev requested changes

2022-12-07 06:36 UTC, igorkamyshev commented on .changeset/brave-rats-fetch.md
> +'@farfetched/react': minor
So, now it is two changes 🤗 old one and new one. I assume, we can delete one of them.

2022-12-07 08:38 UTC, Bricks666 commented
Oh sorry, didn't notice. I fixed it

2022-12-07 08:58 UTC, igorkamyshev approved these changes
Great, thanks 🤗

It'll be released in a couple of days with farfetched@0.4

2022-12-07 08:58 UTC, merged